detecte homemaker

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 detect_OS() {
     os_name=`uname -s`
@@ -12,6 +12,8 @@ detect_OS() {
 
     echo OS is $os_type
 }
+
+command -v homemaker >/dev/null 2>&1 || { echo >&2 "require homemaker but it's not installed.  Aborting."; exit 1; }
 
 detect_OS
 
